### ISSUE TITLE
XML example doesn't display correctly in README.md

### ISSUE THREAD

**Issue by tobyWorland** [rpgoldman/xmls#4]
Looks like it's because GitHub ignores unrecognised tags inside `<pre>` tags.

Is there any reason why README.md has to use HTML tags for formatting? The XML can be escaped with `&lt;` and `&gt;` but it would be simpler to just use markdown syntax instead. 

> ![xml-example](https://user-images.githubusercontent.com/47527939/134442233-d8136702-5413-4690-b99d-cf3984ffed7c.png)

**Comment by rpgoldman** [comment]
Fixed by https://github.com/rpgoldman/xmls/commit/c85ca8b2403da67307cac7db158b0b3c09a1d2ac

The reason there are HTML tags in there is that this was hastily translated from HTML into Markdown: the XMLS library is older than Markdown!
