### ISSUE TITLE
attribute namespace prefix lost upon parsing

### ISSUE THREAD

**Issue by thomp** [rpgoldman/xmls#5]
Is it desirable to retain namespace data for attributes? In the example below, the 'style' namespace prefix seems to vanish upon parsing.

    > (xmls:parse "<text:list-style style:name=\"L1\"></text:list-style>")
    #S(XMLS:NODE :NAME "list-style" :NS "text" :ATTRS (("name" "L1")) :CHILDREN NIL)

**Comment by rpgoldman** [comment]
I don’t `_object_ to fixing this, but I don’t have the time to work on it at present. I would accept a pull request, if you would like to offer one.

I had a quick look at the source code, and didn’t find right away the place where the namespace prefix is stripped off. 

A concern is that the data structures in the original code are alist-like, so extending the attribute list to accept a namespace is harder than it was to add a namespace to elements, which are structures.  But it may be ok to just extend the attribute lists to have a property list after the value.
